### ISSUE TITLE
CentOS7 编译后执行出错

### ISSUE THREAD

**Issue by archerhu77** [shizhuolin/PyCTP#10]
CentOS7
用python3 setup.py build
python3 setup.py install
编译安装成功

但是在测试python3 test_PyCTP.py的时候报错：
ImportError: /usr/lib64/python3.6/site-packages/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

**Comment by shizhuolin** [comment]
同一目录必须存在ctp官方提供的两个so库文件



Sent from my Mi phone
On archerhu77 <notifications@github.com>, Jan 29, 2019 3:43 PM wrote:

CentOS7
用python3 setup.py build
python3 setup.py install
编译安装成功

但是在测试python3 test_PyCTP.py的时候报错：
ImportError: /usr/lib64/python3.6/site-packages/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

**Comment by archerhu77** [comment]
有的

[scripts-3.6]$ ll
total 4548
-rw-r--r--. 1 root root 1609512 Jan 29 15:46 libthostmduserapi.so
-rw-r--r--. 1 root root 3012577 Jan 29 15:46 libthosttraderapi.so
-rwxr-xr-x. 1 root root   30522 Jan 29 15:40 test_PyCTP.py
[scripts-3.6]$ python3 test_PyCTP.py 
Traceback (most recent call last):
  File "test_PyCTP.py", line 10, in <module>
    import PyCTP
ImportError: /usr/lib64/python3.6/site-packages/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

不过一样出错

**Comment by shizhuolin** [comment]
PyCTP.cpython-36m-x86_64-linux-gnu.so<http://64-linux-gnu.so> 这个文件也在ctp库同一路径么？ 只要这三个文件都在同目录, test,文件也在同一目录，按说不应该存在找不到符号定义才对。毕竟你都编译成功了，要是库有问题编译就会失败。



Sent from my Mi phone
On archerhu77 <notifications@github.com>, Jan 29, 2019 4:09 PM wrote:

有的

[scripts-3.6]$ ll
total 4548
-rw-r--r--. 1 root root 1609512 Jan 29 15:46 libthostmduserapi.so
-rw-r--r--. 1 root root 3012577 Jan 29 15:46 libthosttraderapi.so
-rwxr-xr-x. 1 root root 30522 Jan 29 15:40 test_PyCTP.py
[scripts-3.6]$ python3 test_PyCTP.py
Traceback (most recent call last):
File "test_PyCTP.py", line 10, in
import PyCTP
ImportError: /usr/lib64/python3.6/site-packages/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

不过一样出错

**Comment by archerhu77** [comment]
我把您说的文件也拷贝到这个目录了，但是也不行，把所有.so都变成可执行也不行

[scripts-3.6]$ chmod +x *.so
[scripts-3.6]$ ll
total 6784
-rwxr-xr-x. 1 root root 1609512 Jan 29 15:46 libthostmduserapi.so
-rwxr-xr-x. 1 root root 3012577 Jan 29 15:46 libthosttraderapi.so
-rwxr-xr-x. 1 root root 2285776 Jan 29 16:45 PyCTP.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x. 1 root root   30522 Jan 29 15:40 test_PyCTP.py
[scripts-3.6]$ python3 test_PyCTP.py 
Traceback (most recent call last):
  File "test_PyCTP.py", line 10, in <module>
    import PyCTP
ImportError: /root/PyCTP/build/scripts-3.6/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

**Comment by shizhuolin** [comment]
奇怪了，我手里没有centos 7,py36环境，一直用的是py34, centos7, 但不应该如此才对，只要编译能过，就不应该找不到链接符号。编译过程确定没有出现异常报错么？



Sent from my Mi phone
On archerhu77 <notifications@github.com>, Jan 29, 2019 4:46 PM wrote:

我把您说的文件也拷贝到这个目录了，但是也不行，把所有.so都变成可执行也不行

[scripts-3.6]$ chmod +x *.so
[scripts-3.6]$ ll
total 6784
-rwxr-xr-x. 1 root root 1609512 Jan 29 15:46 libthostmduserapi.so
-rwxr-xr-x. 1 root root 3012577 Jan 29 15:46 libthosttraderapi.so
-rwxr-xr-x. 1 root root 2285776 Jan 29 16:45 PyCTP.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x. 1 root root 30522 Jan 29 15:40 test_PyCTP.py
[scripts-3.6]$ python3 test_PyCTP.py
Traceback (most recent call last):
File "test_PyCTP.py", line 10, in
import PyCTP
ImportError: /root/PyCTP/build/scripts-3.6/PyCTP.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

**Comment by archerhu77** [comment]
编译没有出错，我这台还是干净的CentoOS7

**Comment by archerhu77** [comment]
我搞了好多天，还是没能解决问题

**Comment by archerhu77** [comment]
有没有办法直接跟您沟通DEBUG？

**Comment by shizhuolin** [comment]
我qq,   383193853<tel:383193853> 这几天过年有点忙，几天后我看看



Sent from my Mi phone
On archerhu77 <notifications@github.com>, Feb 9, 2019 3:14 PM wrote:

有没有办法直接跟您沟通DEBUG？

**Comment by lbrein** [comment]
383193853 被大量群众举报。。。。。 这个啥意思？

**Comment by shizhuolin** [comment]
举报？不明白，pyctp开源不收费的啊，也没任何衍生服务收费。



Sent from my Mi phone
On lbrein <notifications@github.com>, Jun 13, 2019 6:52 PM wrote:

383193853 被大量群众举报。。。。。 这个啥意思？

**Comment by lbrein** [comment]
加你的qq的时候，显示的信息....

**Comment by zhaoruixue** [comment]
15810106883




------------------ 原始邮件 ------------------
发件人: "lbrein"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 下午2:06
收件人: "shizhuolin/PyCTP"<PyCTP@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [shizhuolin/PyCTP] CentOS7 编译后执行出错 (#10)




加你的qq的时候，显示的信息....
